Traceback (most recent call last):
  File "/Users/caballero/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/caballero/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/caballero/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/caballero/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/caballero/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/caballero/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/caballero/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/caballero/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
!pip install playsound
from playsound import playsound
playsound('data/D_PowerChords_95_SP.wav')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [9][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mpip install playsound[39m[38;5;124m'[39m)
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mplaysound[39;00m [38;5;28;01mimport[39;00m playsound
[0;32m----> 3[0m [43mplaysound[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mdata/D_PowerChords_95_SP.wav[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/playsound.py:244[0m, in [0;36m<lambda>[0;34m(sound, block)[0m
[1;32m    242[0m         [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m    243[0m             logger[38;5;241m.[39mwarning([38;5;124m"[39m[38;5;124mplaysound is relying on a python 2 subprocess. Please use `pip3 install PyObjC` if you want playsound to run more efficiently.[39m[38;5;124m"[39m)
[0;32m--> 244[0m             playsound [38;5;241m=[39m [38;5;28;01mlambda[39;00m sound, block [38;5;241m=[39m [38;5;28;01mTrue[39;00m: [43m_playsoundAnotherPython[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43msound[49m[43m,[49m[43m [49m[43mblock[49m[43m,[49m[43m [49m[43mmacOS[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m    245[0m [38;5;28;01melse[39;00m:
[1;32m    246[0m     playsound [38;5;241m=[39m _playsoundNix

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/playsound.py:229[0m, in [0;36m_playsoundAnotherPython[0;34m(otherPython, sound, block, macOS)[0m
[1;32m    227[0m t[38;5;241m.[39mstart()
[1;32m    228[0m [38;5;28;01mif[39;00m block:
[0;32m--> 229[0m     [43mt[49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[43m)[49m

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/playsound.py:218[0m, in [0;36m_playsoundAnotherPython.<locals>.PropogatingThread.join[0;34m(self, timeout)[0m
[1;32m    216[0m [38;5;28msuper[39m()[38;5;241m.[39mjoin(timeout)
[1;32m    217[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mexc:
[0;32m--> 218[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39mexc
[1;32m    219[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mret

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/playsound.py:211[0m, in [0;36m_playsoundAnotherPython.<locals>.PropogatingThread.run[0;34m(self)[0m
[1;32m    209[0m [38;5;28mself[39m[38;5;241m.[39mexc [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    210[0m [38;5;28;01mtry[39;00m:
[0;32m--> 211[0m     [38;5;28mself[39m[38;5;241m.[39mret [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_target[49m[43m([49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_args[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_kwargs[49m[43m)[49m
[1;32m    212[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[1;32m    213[0m     [38;5;28mself[39m[38;5;241m.[39mexc [38;5;241m=[39m e

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/playsound.py:226[0m, in [0;36m_playsoundAnotherPython.<locals>.<lambda>[0;34m()[0m
[1;32m    223[0m     [38;5;28;01mraise[39;00m PlaysoundException([38;5;124m'[39m[38;5;124mCannot find a sound with filename: [39m[38;5;124m'[39m [38;5;241m+[39m sound)
[1;32m    225[0m playsoundPath [38;5;241m=[39m abspath(getsourcefile([38;5;28;01mlambda[39;00m: [38;5;241m0[39m))
[0;32m--> 226[0m t [38;5;241m=[39m PropogatingThread(target [38;5;241m=[39m [38;5;28;01mlambda[39;00m: [43mcheck_call[49m[43m([49m[43m[[49m[43motherPython[49m[43m,[49m[43m [49m[43mplaysoundPath[49m[43m,[49m[43m [49m[43m_handlePathOSX[49m[43m([49m[43msound[49m[43m)[49m[43m [49m[38;5;28;43;01mif[39;49;00m[43m [49m[43mmacOS[49m[43m [49m[38;5;28;43;01melse[39;49;00m[43m [49m[43msound[49m[43m][49m[43m)[49m)
[1;32m    227[0m t[38;5;241m.[39mstart()
[1;32m    228[0m [38;5;28;01mif[39;00m block:

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/subprocess.py:364[0m, in [0;36mcheck_call[0;34m(*popenargs, **kwargs)[0m
[1;32m    354[0m [38;5;28;01mdef[39;00m [38;5;21mcheck_call[39m([38;5;241m*[39mpopenargs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    355[0m     [38;5;124;03m"""Run command with arguments.  Wait for command to complete.  If[39;00m
[1;32m    356[0m [38;5;124;03m    the exit code was zero then return, otherwise raise[39;00m
[1;32m    357[0m [38;5;124;03m    CalledProcessError.  The CalledProcessError object will have the[39;00m
[0;32m   (...)[0m
[1;32m    362[0m [38;5;124;03m    check_call(["ls", "-l"])[39;00m
[1;32m    363[0m [38;5;124;03m    """[39;00m
[0;32m--> 364[0m     retcode [38;5;241m=[39m [43mcall[49m[43m([49m[38;5;241;43m*[39;49m[43mpopenargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    365[0m     [38;5;28;01mif[39;00m retcode:
[1;32m    366[0m         cmd [38;5;241m=[39m kwargs[38;5;241m.[39mget([38;5;124m"[39m[38;5;124margs[39m[38;5;124m"[39m)

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/subprocess.py:345[0m, in [0;36mcall[0;34m(timeout, *popenargs, **kwargs)[0m
[1;32m    337[0m [38;5;28;01mdef[39;00m [38;5;21mcall[39m([38;5;241m*[39mpopenargs, timeout[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m    338[0m     [38;5;124;03m"""Run command with arguments.  Wait for command to complete or[39;00m
[1;32m    339[0m [38;5;124;03m    timeout, then return the returncode attribute.[39;00m
[1;32m    340[0m 
[0;32m   (...)[0m
[1;32m    343[0m [38;5;124;03m    retcode = call(["ls", "-l"])[39;00m
[1;32m    344[0m [38;5;124;03m    """[39;00m
[0;32m--> 345[0m     [38;5;28;01mwith[39;00m [43mPopen[49m[43m([49m[38;5;241;43m*[39;49m[43mpopenargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m [38;5;28;01mas[39;00m p:
[1;32m    346[0m         [38;5;28;01mtry[39;00m:
[1;32m    347[0m             [38;5;28;01mreturn[39;00m p[38;5;241m.[39mwait(timeout[38;5;241m=[39mtimeout)

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/subprocess.py:969[0m, in [0;36mPopen.__init__[0;34m(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask, pipesize)[0m
[1;32m    965[0m         [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mtext_mode:
[1;32m    966[0m             [38;5;28mself[39m[38;5;241m.[39mstderr [38;5;241m=[39m io[38;5;241m.[39mTextIOWrapper([38;5;28mself[39m[38;5;241m.[39mstderr,
[1;32m    967[0m                     encoding[38;5;241m=[39mencoding, errors[38;5;241m=[39merrors)
[0;32m--> 969[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_execute_child[49m[43m([49m[43margs[49m[43m,[49m[43m [49m[43mexecutable[49m[43m,[49m[43m [49m[43mpreexec_fn[49m[43m,[49m[43m [49m[43mclose_fds[49m[43m,[49m
[1;32m    970[0m [43m                        [49m[43mpass_fds[49m[43m,[49m[43m [49m[43mcwd[49m[43m,[49m[43m [49m[43menv[49m[43m,[49m
[1;32m    971[0m [43m                        [49m[43mstartupinfo[49m[43m,[49m[43m [49m[43mcreationflags[49m[43m,[49m[43m [49m[43mshell[49m[43m,[49m
[1;32m    972[0m [43m                        [49m[43mp2cread[49m[43m,[49m[43m [49m[43mp2cwrite[49m[43m,[49m
[1;32m    973[0m [43m                        [49m[43mc2pread[49m[43m,[49m[43m [49m[43mc2pwrite[49m[43m,[49m
[1;32m    974[0m [43m                        [49m[43merrread[49m[43m,[49m[43m [49m[43merrwrite[49m[43m,[49m
[1;32m    975[0m [43m                        [49m[43mrestore_signals[49m[43m,[49m
[1;32m    976[0m [43m                        [49m[43mgid[49m[43m,[49m[43m [49m[43mgids[49m[43m,[49m[43m [49m[43muid[49m[43m,[49m[43m [49m[43mumask[49m[43m,[49m
[1;32m    977[0m [43m                        [49m[43mstart_new_session[49m[43m)[49m
[1;32m    978[0m [38;5;28;01mexcept[39;00m:
[1;32m    979[0m     [38;5;66;03m# Cleanup if the child failed starting.[39;00m
[1;32m    980[0m     [38;5;28;01mfor[39;00m f [38;5;129;01min[39;00m [38;5;28mfilter[39m([38;5;28;01mNone[39;00m, ([38;5;28mself[39m[38;5;241m.[39mstdin, [38;5;28mself[39m[38;5;241m.[39mstdout, [38;5;28mself[39m[38;5;241m.[39mstderr)):

File [0;32m~/opt/anaconda3/envs/teaching/lib/python3.10/subprocess.py:1845[0m, in [0;36mPopen._execute_child[0;34m(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)[0m
[1;32m   1843[0m     [38;5;28;01mif[39;00m errno_num [38;5;241m!=[39m [38;5;241m0[39m:
[1;32m   1844[0m         err_msg [38;5;241m=[39m os[38;5;241m.[39mstrerror(errno_num)
[0;32m-> 1845[0m     [38;5;28;01mraise[39;00m child_exception_type(errno_num, err_msg, err_filename)
[1;32m   1846[0m [38;5;28;01mraise[39;00m child_exception_type(err_msg)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python'
FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python'

